/* Ofuq PWA service worker */
const CACHE_NAME = 'ofuq-457c268ffbc5';
// App shell: base + key entry shells (login/offline) so cold offline launch works.
const base = new URL('.', self.location.href).href;
const PRECACHE_URLS = [base, base + 'offline', base + 'login', base + 'manifest.json', base + 'manifest-menu.json', base + 'icon-192.png', base + 'icon-512.png', base + 'favicon.ico', base + 'apple-touch-icon.png', base + 'precache-manifest.json'];

/* ---- Precaching the built bundles (the fix for "offline can't navigate") ----
   The app is an SSR build: there is no static index.html, so the shell HTML is
   generated by the server and the hashed JS/CSS bundles live in /assets. They
   were never precached, so offline the browser painted the cached HTML but the
   scripts 404'd -> no hydration -> links dead and a reload rendered nothing.
   `vite build` now emits precache-manifest.json listing every bundle; we cache
   them all so the app boots and routes normally without a network. */
async function cacheWithConcurrency(cache, urls, limit) {
  if (!urls || !urls.length) return;
  const queue = urls.slice();
  const worker = async () => {
    for (;;) {
      const url = queue.shift();
      if (url === undefined) return;
      try {
        const res = await fetch(url, { cache: 'reload' });
        // Tolerate individual failures: a single 404 must not abort the run, and
        // a quota error just ends this worker's loop while others continue.
        if (!res || !res.ok) continue;
        await cache.put(url, res);
      } catch {
        /* skip this url */
      }
    }
  };
  const n = Math.max(1, Math.min(limit, queue.length));
  await Promise.all(Array.from({ length: n }, () => worker()));
}

async function precacheUrls() {
  // Preferred: build manifest with the exact hashed filenames.
  let all = [];
  try {
    const res = await fetch(base + 'precache-manifest.json', { cache: 'no-cache' });
    if (res && res.ok) {
      const json = await res.json();
      if (json && Array.isArray(json.assets) && json.assets.length) {
        all = json.assets.map((u) => (u.startsWith('http') ? u : new URL(u, base).href));
      }
    }
  } catch {}

  // What the shell HTML actually references — the entry script and CSS. These are
  // cached FIRST so that if the storage quota runs out mid-precache the app can
  // still boot and be navigable offline.
  let critical = [];
  try {
    const res = await fetch(base, { cache: 'reload' });
    const html = await res.text();
    const found = new Set();
    const re = /(?:src|href)=["']([^"']*\/assets\/[^"']+)["']/g;
    let m;
    while ((m = re.exec(html))) found.add(new URL(m[1], base).href);
    critical = [...found];
  } catch {
    /* dev server without a shell — manifest order is used as-is */
  }

  const criticalSet = new Set(critical);
  const rest = all.filter((u) => !criticalSet.has(u));
  return { critical, rest };
}


/* ---- Offline-first data layer: cache Supabase reads, queue writes ----
   يغطي النظام كامل دون تعديل الصفحات: أي قراءة GET تُخبّأ لكل مستخدم،
   وأي كتابة دون اتصال تُحفظ في نفس صندوق التطبيق (IndexedDB) ليُزامنها. */
const API_CACHE_PREFIX = 'ofuq-api-';
const OUTBOX_DB = 'shamel-offline';

function djb2(str) {
  let h = 5381;
  for (let i = 0; i < str.length; i++) h = ((h << 5) + h + str.charCodeAt(i)) >>> 0;
  return h.toString(36);
}
function apiUserKey(req) {
  const auth = req.headers.get('authorization') || '';
  const key = req.headers.get('apikey') || '';
  return djb2(auth + '|' + key);
}
function restInfo(req) {
  try {
    const u = new URL(req.url);
    if (!u.pathname.includes('/rest/v1/')) return null;
    const after = u.pathname.split('/rest/v1/')[1] || '';
    const table = after.split('/')[0].split('?')[0];
    if (!table || table === 'rpc') return null;
    return { url: u, table };
  } catch {
    return null;
  }
}
function openOutboxDb() {
  return new Promise((resolve, reject) => {
    try {
      const r = indexedDB.open(OUTBOX_DB, 2);
      r.onupgradeneeded = () => {
        const db = r.result;
        if (!db.objectStoreNames.contains('outbox')) {
          const st = db.createObjectStore('outbox', { keyPath: 'id', autoIncrement: true });
          st.createIndex('by-status', 'status', { unique: false });
        }
        if (!db.objectStoreNames.contains('kv')) db.createObjectStore('kv', { keyPath: 'key' });
      };
      r.onsuccess = () => resolve(r.result);
      r.onerror = () => reject(r.error);
    } catch (e) {
      reject(e);
    }
  });
}
function idbAdd(entry) {
  return openOutboxDb().then(
    (db) =>
      new Promise((resolve, reject) => {
        try {
          const t = db.transaction('outbox', 'readwrite');
          const q = t.objectStore('outbox').add(entry);
          q.onsuccess = () => resolve(q.result);
          q.onerror = () => reject(q.error);
          t.oncomplete = () => {
            try { db.close(); } catch {}
          };
        } catch (e) {
          try { db.close(); } catch {}
          reject(e);
        }
      }),
  );
}
function tempId() {
  return 'queued-' + Date.now().toString(36) + '-' + Math.floor(Math.random() * 1e6).toString(36);
}
async function queueMutation(req, info) {
  let body = null;
  try {
    body = await req.clone().json();
  } catch {
    body = null;
  }
  let recordId = null;
  try {
    for (const [, v] of info.url.searchParams) {
      const m = String(v).match(/^eq\.(.+)$/);
      if (m) { recordId = decodeURIComponent(m[1]); break; }
    }
  } catch {}
  const now = new Date().toISOString();
  const prefer = req.headers.get('prefer') || '';
  const wantsRows = prefer.indexOf('return=representation') >= 0;
  const method = req.method;
  const entries = [];
  const rows = [];
  if (method === 'DELETE') {
    entries.push({ table: info.table, op: 'delete', data: null, recordId, label: 'حذف دون اتصال: ' + info.table, created_at: now, status: 'pending', attempts: 0, error: null });
  } else if (body != null) {
    const list = Array.isArray(body) ? body : [body];
    const clientIds = [];
    for (const row of list) {
      const r = row && typeof row === 'object' ? { ...row } : { value: row };
      if (!r.id) r.id = tempId();
      if (!r.created_at) r.created_at = now;
      clientIds.push(String(r.id));
      rows.push(r);
    }
    if (method === 'PATCH' || method === 'PUT') {
      entries.push({ table: info.table, op: 'update', data: rows.length === 1 ? rows[0] : rows, recordId, clientIds, label: 'تعديل دون اتصال: ' + info.table, created_at: now, status: 'pending', attempts: 0, error: null });
    } else {
      entries.push({ table: info.table, op: 'insert', data: rows.length === 1 ? rows[0] : rows, recordId: null, clientIds, label: 'إضافة دون اتصال: ' + info.table, created_at: now, status: 'pending', attempts: 0, error: null });
    }
  } else {
    return new Response(JSON.stringify({ message: 'offline' }), { status: 503, headers: { 'Content-Type': 'application/json' } });
  }
  for (const e of entries) {
    try {
      await idbAdd(e);
    } catch {
      return new Response(JSON.stringify({ message: 'offline queue full' }), { status: 503, headers: { 'Content-Type': 'application/json' } });
    }
  }
  if (!wantsRows) return new Response(null, { status: method === 'POST' ? 201 : 204 });
  return new Response(JSON.stringify(method === 'DELETE' ? [] : rows), {
    status: method === 'POST' ? 201 : 200,
    headers: { 'Content-Type': 'application/json' },
  });
}
async function cachedRestGet(req) {
  let cache = null;
  try {
    cache = await caches.open(API_CACHE_PREFIX + apiUserKey(req));
  } catch {
    cache = null;
  }
  try {
    const res = await fetch(req);
    if (res && res.status === 200 && cache) {
      try {
        await cache.put(req, res.clone());
        cache.keys().then((keys) => {
          if (keys.length > 300) keys.slice(0, keys.length - 300).forEach((k) => cache.delete(k).catch(() => {}));
        }).catch(() => {});
      } catch {}
    }
    return res;
    } catch (e) {
      if (cache) {
        const hit = await cache.match(req).catch(() => null);
        if (hit) return hit;
      }
      // لا كاش: 503 (وليس 200 فارغاً) حتى لا تُسمّم اللقطات المحلية بصفوف فارغة
      return new Response(JSON.stringify({ message: 'offline-no-cache' }), { status: 503, headers: { 'Content-Type': 'application/json', 'X-Offline-Cache': 'miss' } });
    }
}

/* ---- Web Push notifications ---- */
self.addEventListener('push', (event) => {
  let data = { title: 'أفق', body: '', url: '/notifications', type: 'info' };
  try {
    if (event.data) {
      const parsed = event.data.json();
      data = { ...data, ...parsed };
    }
  } catch {
    // Not JSON — fall back to raw text.
    data.body = event.data ? event.data.text() : '';
  }

  // Phone behavior: vibrate + re-alert on every push (even with the app
  // closed the OS wakes the service worker, shows and buzzes each time).
  const important = data.type === 'warning' || data.type === 'error';
  const options = {
    body: data.body || '',
    icon: base + 'icon-192.png',
    badge: base + 'icon-192.png',
    data: { url: data.url || base + 'notifications' },
    dir: 'rtl',
    lang: 'ar',
    // وسم فريد لكل إشعار: الوسم الثابت كان يدمج الإشعارات المتتالية في واحد
    // فيظن المستخدم أنها لا تصل — الآن يتراكم كل إشعار مستقلًا
    tag: 'shamel-' + (data.type || 'info') + '-' + Date.now() + '-' + Math.floor(Math.random() * 1e6),
    renotify: true,
    vibrate: [200, 100, 200],
    timestamp: Date.now(),
    // التحذيرات تبقى ظاهرة حتى يقرأها المستخدم — كانت تختفي وسط الإشعارات
    requireInteraction: important,
  };

  event.waitUntil(self.registration.showNotification(data.title || 'أفق', options));
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const url = (event.notification.data && event.notification.data.url) || base + 'notifications';
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      for (const client of clientList) {
        if ('focus' in client) return client.focus();
      }
      if (self.clients.openWindow) return self.clients.openWindow(url);
    }),
  );
});

self.addEventListener('install', (event) => {
  self.skipWaiting();
  event.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE_NAME);
      const { critical, rest } = await precacheUrls();
      // Shell + entry bundles first, then everything else. Per-URL failures are
      // tolerated so one bad asset cannot wipe the whole precache.
      await cacheWithConcurrency(cache, PRECACHE_URLS, 6);
      await cacheWithConcurrency(cache, critical, 6);
      await cacheWithConcurrency(cache, rest, 8);
    })().catch(() => {}),
  );
});

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    // نحافظ على كاش قراءات API (تعمل دون اتصال) ونحذف نسخ هيكل التطبيق القديمة فقط
    caches.keys().then((keys) => Promise.all(keys.filter((k) => k !== CACHE_NAME && k.indexOf(API_CACHE_PREFIX) !== 0).map((k) => caches.delete(k)))),
  );
  self.clients.claim();
  // لا نفرض إعادة تحميل التبويبات عند تحديث SW — كانت تمسح السلات والنماذج.
  // التحديث يتم عبر SKIP_WAITING + controllerchange في التطبيق.
});

/* App shell first, with network fallback for navigation requests. */
function offlineDocument() {
  // Only reached if even the shell was never cached. Returning a real document
  // keeps the user inside the app instead of the browser's error page.
  const html = `<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1"><title>أفق</title>
<style>body{font-family:system-ui,sans-serif;display:grid;place-items:center;min-height:100vh;margin:0;background:#f8fafc;color:#0f172a}
div{text-align:center;padding:24px}h1{font-size:20px}p{color:#475569;font-size:14px}</style></head>
<body><div><h1>لا يوجد اتصال بالإنترنت</h1>
<p>لم يتم تخزين هذه الشاشة بعد. اتصل بالإنترنت مرة واحدة لفتحها، ثم ستعمل دون اتصال.</p>
<p><button onclick="location.reload()">إعادة المحاولة</button></p></div></body></html>`;
  return new Response(html, { status: 200, headers: { 'Content-Type': 'text/html; charset=utf-8' } });
}

self.addEventListener('fetch', (event) => {
  const req = event.request;

  // طبقة البيانات دون اتصال (Supabase REST): قبل أي فحص origin لأن الخادم خارجي
  try {
    const info = restInfo(req);
    if (info) {
      if (req.method === 'GET') {
        event.respondWith(cachedRestGet(req));
        return;
      }
      if (req.method === 'POST' || req.method === 'PATCH' || req.method === 'PUT' || req.method === 'DELETE') {
        event.respondWith(
          fetch(req).catch(() => queueMutation(req, info)),
        );
        return;
      }
      return;
    }
  } catch {
    /* ignore */
  }

  if (req.method !== 'GET') return;

  const url = new URL(req.url);

  // Never cache API / Supabase / gateway calls.
  if (url.origin !== self.location.origin) return;
  if (url.pathname.startsWith('/api/') || url.pathname.includes('supabase') || url.pathname.includes('.output')) return;

  if (req.mode === 'navigate') {
    event.respondWith(
      (async () => {
        try {
          const res = await fetch(req);
          const copy = res.clone();
          // Refresh the cached shell so the next offline launch matches this build.
          caches.open(CACHE_NAME).then((cache) => cache.put(base, copy)).catch(() => {});
          return res;
        } catch {
          // Offline: serve the cached shell for whatever path was requested. The
          // router reads window.location on boot, so the correct page renders.
          const cache = await caches.open(CACHE_NAME);
          const hit = (await cache.match(req, { ignoreSearch: true })) || (await cache.match(base)) || (await cache.match(base + 'offline'));
          return hit || offlineDocument();
        }
      })(),
    );
    return;
  }

  event.respondWith(
    caches.match(req).then((cached) => {
      if (cached) return cached;
      return fetch(req)
        .then((res) => {
          if (res && res.status === 200 && res.type === 'basic') {
            const copy = res.clone();
            caches.open(CACHE_NAME).then((cache) => cache.put(req, copy)).catch(() => {});
          }
          return res;
        })
        // Returning undefined here made respondWith() reject, which the browser
        // surfaces as a hard network error and a blank page. Always answer.
        .catch(() => cached || new Response('', { status: 504, statusText: 'Offline' }));
    }),
  );
});
